// Code generated by protoc-gen-go. DO NOT EDIT.
// source: machine/machine.proto

package machine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instruction struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Operand              int32    `protobuf:"varint,2,opt,name=operand,proto3" json:"operand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instruction) Reset()         { *m = Instruction{} }
func (m *Instruction) String() string { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()    {}
func (*Instruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{0}
}

func (m *Instruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instruction.Unmarshal(m, b)
}
func (m *Instruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instruction.Marshal(b, m, deterministic)
}
func (m *Instruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instruction.Merge(m, src)
}
func (m *Instruction) XXX_Size() int {
	return xxx_messageInfo_Instruction.Size(m)
}
func (m *Instruction) XXX_DiscardUnknown() {
	xxx_messageInfo_Instruction.DiscardUnknown(m)
}

var xxx_messageInfo_Instruction proto.InternalMessageInfo

func (m *Instruction) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Instruction) GetOperand() int32 {
	if m != nil {
		return m.Operand
	}
	return 0
}

type InstructionSet struct {
	Instructions         []*Instruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InstructionSet) Reset()         { *m = InstructionSet{} }
func (m *InstructionSet) String() string { return proto.CompactTextString(m) }
func (*InstructionSet) ProtoMessage()    {}
func (*InstructionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{1}
}

func (m *InstructionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstructionSet.Unmarshal(m, b)
}
func (m *InstructionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstructionSet.Marshal(b, m, deterministic)
}
func (m *InstructionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstructionSet.Merge(m, src)
}
func (m *InstructionSet) XXX_Size() int {
	return xxx_messageInfo_InstructionSet.Size(m)
}
func (m *InstructionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_InstructionSet.DiscardUnknown(m)
}

var xxx_messageInfo_InstructionSet proto.InternalMessageInfo

func (m *InstructionSet) GetInstructions() []*Instruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type Result struct {
	Output               float32  `protobuf:"fixed32,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_84b4f59d98cc997c, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetOutput() float32 {
	if m != nil {
		return m.Output
	}
	return 0
}

func init() {
	proto.RegisterType((*Instruction)(nil), "machine.Instruction")
	proto.RegisterType((*InstructionSet)(nil), "machine.InstructionSet")
	proto.RegisterType((*Result)(nil), "machine.Result")
}

func init() {
	proto.RegisterFile("machine/machine.proto", fileDescriptor_84b4f59d98cc997c)
}

var fileDescriptor_84b4f59d98cc997c = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xcd, 0x8a, 0xad, 0xce, 0x8a, 0xc2, 0xa0, 0x6b, 0xd8, 0x53, 0xc8, 0x29, 0xa7, 0x55,
	0x56, 0x0f, 0xde, 0x45, 0x41, 0xc1, 0x4b, 0xf2, 0x04, 0xb5, 0x0e, 0x1a, 0x70, 0x93, 0x92, 0x4e,
	0xc4, 0x37, 0xf0, 0xb5, 0x85, 0x6e, 0xbb, 0x76, 0xa1, 0xa7, 0xe4, 0xfb, 0xf9, 0xf9, 0xf8, 0x19,
	0xb8, 0xdc, 0x54, 0xf5, 0xa7, 0x0f, 0x74, 0xdd, 0xbf, 0xab, 0x26, 0x45, 0x8e, 0x58, 0xf6, 0xa8,
	0x1f, 0x60, 0xfe, 0x1c, 0x5a, 0x4e, 0xb9, 0x66, 0x1f, 0x03, 0x2e, 0xe1, 0x38, 0x36, 0x94, 0x2a,
	0x8e, 0x49, 0x0a, 0x25, 0xcc, 0x89, 0xdd, 0x31, 0x4a, 0x28, 0xbb, 0x7f, 0x78, 0x97, 0x33, 0x25,
	0xcc, 0x91, 0x1d, 0x50, 0xbf, 0xc0, 0xd9, 0x48, 0xe2, 0x88, 0xf1, 0x1e, 0x4e, 0xfd, 0x7f, 0xd2,
	0x4a, 0xa1, 0x0e, 0xcd, 0x7c, 0x7d, 0xb1, 0x1a, 0x56, 0x8c, 0xea, 0x76, 0xaf, 0xa9, 0x15, 0x14,
	0x96, 0xda, 0xfc, 0xc5, 0xb8, 0x80, 0x22, 0x66, 0x6e, 0x32, 0x77, 0x4b, 0x66, 0xb6, 0xa7, 0xf5,
	0xaf, 0x80, 0xf2, 0x75, 0xeb, 0xc1, 0x3b, 0x28, 0x1f, 0x7f, 0xa8, 0xce, 0x4c, 0x38, 0x29, 0x5f,
	0x9e, 0xef, 0xd2, 0xad, 0x55, 0x1f, 0x18, 0x81, 0x4f, 0xb0, 0x70, 0x94, 0xbe, 0x29, 0x39, 0x4e,
	0x54, 0x6d, 0x7c, 0xf8, 0x18, 0x24, 0x57, 0x53, 0x12, 0x47, 0x3c, 0xe1, 0xb9, 0x11, 0x6f, 0x45,
	0x77, 0xcc, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0xbc, 0x16, 0xfa, 0x65, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MachineClient is the client API for Machine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MachineClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (Machine_ExecuteClient, error)
	ServerStreamingExecute(ctx context.Context, in *InstructionSet, opts ...grpc.CallOption) (Machine_ServerStreamingExecuteClient, error)
}

type machineClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineClient(cc grpc.ClientConnInterface) MachineClient {
	return &machineClient{cc}
}

func (c *machineClient) Execute(ctx context.Context, opts ...grpc.CallOption) (Machine_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[0], "/machine.Machine/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineExecuteClient{stream}
	return x, nil
}

type Machine_ExecuteClient interface {
	Send(*Instruction) error
	CloseAndRecv() (*Result, error)
	grpc.ClientStream
}

type machineExecuteClient struct {
	grpc.ClientStream
}

func (x *machineExecuteClient) Send(m *Instruction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *machineExecuteClient) CloseAndRecv() (*Result, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *machineClient) ServerStreamingExecute(ctx context.Context, in *InstructionSet, opts ...grpc.CallOption) (Machine_ServerStreamingExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Machine_serviceDesc.Streams[1], "/machine.Machine/ServerStreamingExecute", opts...)
	if err != nil {
		return nil, err
	}
	x := &machineServerStreamingExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Machine_ServerStreamingExecuteClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type machineServerStreamingExecuteClient struct {
	grpc.ClientStream
}

func (x *machineServerStreamingExecuteClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MachineServer is the server API for Machine service.
type MachineServer interface {
	Execute(Machine_ExecuteServer) error
	ServerStreamingExecute(*InstructionSet, Machine_ServerStreamingExecuteServer) error
}

// UnimplementedMachineServer can be embedded to have forward compatible implementations.
type UnimplementedMachineServer struct {
}

func (*UnimplementedMachineServer) Execute(srv Machine_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedMachineServer) ServerStreamingExecute(req *InstructionSet, srv Machine_ServerStreamingExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamingExecute not implemented")
}

func RegisterMachineServer(s *grpc.Server, srv MachineServer) {
	s.RegisterService(&_Machine_serviceDesc, srv)
}

func _Machine_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MachineServer).Execute(&machineExecuteServer{stream})
}

type Machine_ExecuteServer interface {
	SendAndClose(*Result) error
	Recv() (*Instruction, error)
	grpc.ServerStream
}

type machineExecuteServer struct {
	grpc.ServerStream
}

func (x *machineExecuteServer) SendAndClose(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *machineExecuteServer) Recv() (*Instruction, error) {
	m := new(Instruction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Machine_ServerStreamingExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstructionSet)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MachineServer).ServerStreamingExecute(m, &machineServerStreamingExecuteServer{stream})
}

type Machine_ServerStreamingExecuteServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type machineServerStreamingExecuteServer struct {
	grpc.ServerStream
}

func (x *machineServerStreamingExecuteServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

var _Machine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "machine.Machine",
	HandlerType: (*MachineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _Machine_Execute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamingExecute",
			Handler:       _Machine_ServerStreamingExecute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "machine/machine.proto",
}
